#!/bin/sh

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

regex='^\[[0-9]{6}\] [A-Z].+'

if ! echo "$commit_msg" | grep -Eq "$regex"; then
  echo "❌ Invalid commit message – please fix it 🙂"
  echo "✅ Commit message must be in format: \033[1;35m[000000] Capitalized message\033[0m"
  exit 1
fi
